/**
 * Generated by pnpm gen:types from the FastAPI OpenAPI schema.
 * Run `pnpm gen:types` to regenerate when the backend contract changes.
 *
 * This is a hand-crafted stub reflecting the portal routes (PORTAL-003).
 * Replace with the real generated file once the backend is reachable.
 */

export interface paths {
  '/api/v1/portal/login': {
    post: {
      requestBody: {
        content: {
          'application/json': { email: string; password: string }
        }
      }
      responses: {
        200: { content: { 'application/json': { id: string; email: string } } }
        401: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/logout': {
    post: {
      responses: {
        204: { content: never }
        401: { content: { 'application/json': { detail: string } } }
        403: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/me': {
    get: {
      responses: {
        200: { content: { 'application/json': { id: string; email: string } } }
        401: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/csrf': {
    get: {
      responses: {
        200: { content: { 'application/json': { token: string } } }
        401: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/jobs': {
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
          status?: string
          date_from?: string
          date_to?: string
        }
      }
      responses: {
        200: { content: { 'application/json': JobDetailResponse[] } }
        304: { content: never }
        401: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/stats': {
    get: {
      parameters: {
        query?: { month?: string }
      }
      responses: {
        200: { content: { 'application/json': StatsResponse } }
        401: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/jobs/{job_id}/result': {
    get: {
      parameters: {
        path: { job_id: string }
      }
      responses: {
        200: { content: { 'application/json': JobResultResponse } }
        304: { content: never }
        401: { content: { 'application/json': { detail: string } } }
        404: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/photos/{photo_id}/thumb': {
    get: {
      parameters: {
        path: { photo_id: string }
        query?: { w?: number }
      }
      responses: {
        200: { content: { 'image/jpeg': Blob } }
        401: { content: { 'application/json': { detail: string } } }
        404: { content: { 'application/json': { detail: string } } }
        422: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/avarias/pairs': {
    get: {
      parameters: {
        query?: {
          limit?: number
          offset?: number
          status?: string
          asset_code?: string
          date_from?: string
          date_to?: string
        }
      }
      responses: {
        200: { content: { 'application/json': PairsListResponse } }
        401: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/avarias/pairs/{pair_id}': {
    get: {
      parameters: {
        path: { pair_id: string }
      }
      responses: {
        200: { content: { 'application/json': PairDetailResponse } }
        401: { content: { 'application/json': { detail: string } } }
        404: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/avarias/events/{event_id}': {
    get: {
      parameters: { path: { event_id: string } }
      responses: {
        200: { content: { 'application/json': EventStatusResponse } }
        401: { content: { 'application/json': { detail: string } } }
        404: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/avarias/events/{event_id}/ground-truth': {
    patch: {
      parameters: { path: { event_id: string } }
      requestBody: {
        content: { 'application/json': { ground_truth_class: string } }
      }
      responses: {
        200: { content: { 'application/json': { event_id: string; ground_truth_class: string } } }
        401: { content: { 'application/json': { detail: string } } }
        403: { content: { 'application/json': { detail: string } } }
        404: { content: { 'application/json': { detail: string } } }
        422: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/avarias/image': {
    get: {
      parameters: {
        query: { path: string }
      }
      responses: {
        200: { content: { 'image/jpeg': Blob } }
        401: { content: { 'application/json': { detail: string } } }
        404: { content: { 'application/json': { detail: string } } }
        422: { content: { 'application/json': { detail: string } } }
      }
    }
  }

  '/api/v1/portal/run': {
    post: {
      requestBody: {
        content: {
          'application/json': { checklist_id: string }
        }
      }
      responses: {
        202: { content: { 'application/json': { job_id: string; status: string } } }
        401: { content: { 'application/json': { detail: string } } }
        403: { content: { 'application/json': { detail: string } } }
        422: { content: { 'application/json': { detail: string } } }
      }
    }
  }
}

// ── shared response types ────────────────────────────────────────────────────

export interface EventDetailResponse {
  id: string
  asset_code: string
  canonical_angle: string | null
  captured_at: string | null
  moment: string | null
  status: string
  damage_class: string | null
  damage_confidence: number | null
  damage_severity: string | null
  angle_class: string | null
  validation_reason: string | null
  result_json: Record<string, unknown> | null
  source_path: string
  checklist_id: string | null
  ground_truth_class: string | null
  created_at: string
}

export interface PairSummaryResponse {
  id: string
  asset_code: string
  pair_date: string
  status: 'partial' | 'complete'
  saida_event_id: string | null
  retorno_event_id: string | null
  annotated_image_path: string | null
  saida_damage_class: string | null
  saida_damage_severity: string | null
  retorno_damage_class: string | null
  retorno_damage_severity: string | null
  checklist_id: string | null
  has_non_conformity: boolean
  created_at: string
}

export interface PairsListResponse {
  total: number
  items: PairSummaryResponse[]
}

export interface PairDetailResponse {
  id: string
  asset_code: string
  pair_date: string
  status: string
  annotated_image_path: string | null
  saida: EventDetailResponse | null
  retorno: EventDetailResponse | null
  created_at: string
  updated_at: string
}

export interface EventStatusResponse {
  event_id: string
  status: string
  asset_code: string
  checklist_id: string | null
  moment: string | null
  damage_class: string | null
  damage_severity: string | null
  damage_confidence: number | null
  validation_reason: string | null
  source_path: string | null
  baseline_source_path: string | null
  observation: string | null
  pair_id: string | null
}

export interface JobDetailResponse {
  id: string
  checklist_id: string
  status: 'pending' | 'running' | 'done' | 'failed'
  created_at: string
  started_at: string | null
  finished_at: string | null
  error: string | null
  result_pdf_path: string | null
  metrics: Record<string, unknown> | null
}

export interface StatsResponse {
  total_done: number
  in_progress: number
  failed: number
  total_cost_usd: number
  accuracy_last_week: number | null
}

export interface ClassificationItemResponse {
  photo_id: string
  field_name: string | null
  confidence: number
  status: string
  label_display: string
  second_best_field: string | null
  second_best_confidence: number | null
}

export interface JobResultResponse {
  job_id: string
  checklist_id: string
  status: string
  started_at: string | null
  finished_at: string | null
  estimated_cost_usd: number | null
  result_pdf_path: string | null
  error: string | null
  classifications: ClassificationItemResponse[]
  inconclusivas: ClassificationItemResponse[]
}
